# Generated by Django 4.1.6 on 2023-03-22 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employees',
            options={'verbose_name': 'Employees', 'verbose_name_plural': 'Employees'},
        ),
    ]
