# Generated by Django 4.2 on 2023-04-13 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='items',
            options={'verbose_name': 'Items', 'verbose_name_plural': 'Items'},
        ),
    ]
