# Generated by Django 4.2 on 2023-04-14 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_items_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='items',
            old_name='image_url',
            new_name='image',
        ),
    ]
