# Generated by Django 4.1.6 on 2023-03-21 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_reservation_current_location_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret_login', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'AdminLogin',
                'verbose_name_plural': 'AdminLogin',
            },
        ),
        migrations.AlterModelOptions(
            name='reservation',
            options={'verbose_name': 'Reservation', 'verbose_name_plural': 'Reservation'},
        ),
        migrations.AlterField(
            model_name='reservation',
            name='current_location',
            field=models.CharField(choices=[('Bamenda', 'Bamenda'), ('Douala', 'Douala'), ('Yaounde', 'Yaounde'), ('Buea', 'Buea')], default='Bamenda', max_length=30),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='destination',
            field=models.CharField(choices=[('Bamenda', 'Bamenda'), ('Douala', 'Douala'), ('Yaounde', 'Yaounde'), ('Buea', 'Buea')], default='Douala', max_length=30),
        ),
    ]
