# Generated by Django 4.1.5 on 2023-03-21 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_adminlogin_alter_reservation_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='current_location',
            field=models.CharField(choices=[('Bamenda', 'Bamenda'), ('Douala', 'Douala'), ('Yaounde', 'Yaounde'), ('Buea', 'Buea')], default='Bamenda', max_length=7),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='destination',
            field=models.CharField(choices=[('Bamenda', 'Bamenda'), ('Douala', 'Douala'), ('Yaounde', 'Yaounde'), ('Buea', 'Buea')], default='Douala', max_length=7),
        ),
    ]
