# Generated by Django 4.1.6 on 2023-03-21 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_adminlogin_alter_reservation_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=15, verbose_name='phone number')),
                ('email', models.CharField(max_length=50)),
                ('destination', models.CharField(choices=[('Bamenda', 'Bamenda'), ('Douala', 'Douala'), ('Yaounde', 'Yaounde'), ('Buea', 'Buea')], default='Bamenda', max_length=30)),
                ('password', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Manager',
                'verbose_name_plural': 'Manager',
            },
        ),
    ]
