# Generated by Django 4.1.5 on 2023-03-23 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_reservation_current_location_and_more'),
        ('myapp', '0004_manager'),
    ]

    operations = [
    ]
