# Generated by Django 4.1.6 on 2023-04-06 12:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
