# Generated by Django 4.1.5 on 2023-04-07 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_blog_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='notes',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
