# Generated by Django 4.1.6 on 2023-02-14 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='features',
            name='details',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='features',
            name='heading',
            field=models.CharField(max_length=50),
        ),
    ]
